# .circleci/config.yml  (CircleCI 2.1)
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: Build Docker image
          command: docker build --progress=plain -t comfy-wan22-template:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag comfy-wan22-template:latest "$DOCKERHUB_USER"/comfy-wan22-template:latest
            docker push "$DOCKERHUB_USER"/comfy-wan22-template:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
